# Generated by Django 5.1.1 on 2024-09-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
        ('base', '0003_user_avatar'),
    ]

    operations = [
    ]
