# Generated by Django 5.1.1 on 2024-09-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_merge_20240930_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
